#!/bin/bash
############################################################
# 
############################################################

function lock {
    scrot /tmp/screen_locked.png
    convert /tmp/screen_locked.png -blur 3x3 /tmp/screen_locked2.png
    i3lock --show-failed-attempts -i /tmp/screen_locked2.png
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && sudo systemctl suspend
        suspend
        ;;
    reboot)
        sudo systemctl reboot
        ;;
    poweroff)
        sudo systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|reboot|poweroff}"
        exit 2
esac

exit 0
